<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Techno-247" failures="1" tests="1" name="test1" time="104.657" errors="0" timestamp="29 Jan 2021 13:36:52 GMT">
  <testcase classname="io.mosip.ivv.orchestrator.Orchestrator" name="run" time="104.287">
    <failure type="java.lang.AssertionError" message="Failed at credential issuance status check Response validation expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Failed at credential issuance status check Response validation expected [true] but found [false]
at io.mosip.ivv.e2e.methods.CheckStatus.run(CheckStatus.java:60)
at io.mosip.ivv.orchestrator.Orchestrator.run(Orchestrator.java:168)
at io.mosip.ivv.orchestrator.TestRunner.startTestRunner(TestRunner.java:55)
at io.mosip.ivv.orchestrator.TestRunner.main(TestRunner.java:30)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- run -->
</testsuite> <!-- test1 -->
