<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-01-13T05:52:48Z" name="Suite1" finished-at="2021-01-13T05:52:48Z" duration-ms="809">
    <groups>
    </groups>
    <test started-at="2021-01-13T05:52:48Z" name="test1" finished-at="2021-01-13T05:52:48Z" duration-ms="809">
      <class name="io.mosip.ivv.orchestrator.Orchestrator">
        <test-method is-config="true" signature="beforeSuite()[pri:0, instance:io.mosip.ivv.orchestrator.Orchestrator@6cc4cdb9]" started-at="2021-01-13T05:52:47Z" name="beforeSuite" finished-at="2021-01-13T05:52:48Z" duration-ms="298" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeSuite -->
        <test-method is-config="true" signature="create_proxy_server()[pri:0, instance:io.mosip.ivv.orchestrator.Orchestrator@6cc4cdb9]" started-at="2021-01-13T05:52:48Z" name="create_proxy_server" finished-at="2021-01-13T05:52:48Z" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- create_proxy_server -->
        <test-method is-config="true" signature="beforeMethod(java.lang.reflect.Method)[pri:0, instance:io.mosip.ivv.orchestrator.Orchestrator@6cc4cdb9]" started-at="2021-01-13T05:52:48Z" name="beforeMethod" finished-at="2021-01-13T05:52:48Z" duration-ms="1" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[private void io.mosip.ivv.orchestrator.Orchestrator.run(int,io.mosip.ivv.core.dtos.Scenario,java.util.HashMap,java.util.HashMap,java.util.Properties) throws java.sql.SQLException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method signature="run(int, io.mosip.ivv.core.dtos.Scenario, java.util.HashMap, java.util.HashMap, java.util.Properties)[pri:0, instance:io.mosip.ivv.orchestrator.Orchestrator@6cc4cdb9]" started-at="2021-01-13T05:52:48Z" name="run" data-provider="ScenarioDataProvider" finished-at="2021-01-13T05:52:48Z" duration-ms="265" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[0]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[io.mosip.ivv.core.dtos.Scenario@56b78e55]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[{LOCK_ATTEMPTS=5, INVALID_EMAIL=mosiptest@, INVALID_SLOT=23:30-23:45, INVALID_PRID=100000000, FUTUREDATE=SYSDATE + 30, SHARELIST=, SYSDATE=System Date, INVALID_DOCID=10000, INVALID_DOCTYPE=ABC, INVALID_MOBILE=1234587m, INVALID_DOCFORMAT=MPEG, INVALID_DOCCATEGORY=POF, INVALID_CENTER=IC01, PASDTDATE=SYSDATE-1}]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[{LOCK_ATTEMPTS=5, INVALID_PREREGISTRATION_ID=18131, OTHER_PERSON_PREREGISTRATION_ID=35353535353, INVALID_EMAIL=mosiptest@, INVALID_SLOT=23:30-23:45, INVALID_PRID=100000000, FUTUREDATE=SYSDATE + 30, SHARELIST=, INVALID_LANG_CODE=English, SYSDATE=System Date, INVALID_DOCID=10000, INVALID_DOCTYPE=ABC, INVALID_MOBILE=1234587m, INVALID_DOCFORMAT=MPEG, INVALID_DOCCATEGORY=POF, INVALID_CENTER=IC01, PASDTDATE=SYSDATE-1}]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[{reportsFolder=\testRun\reports\, bookingBookID=mosip.pre-registration.booking.book, ivv.path.globals.sheet=local/GlobalsSheet.csv, ivv.global.apiversion=1.0, mosip.kernel.keygenerator.asymmetric-algorithm-name=RSA, ivv.path.biometrics.folder=local/data/biometrics/, otpServceID=mosip.identity.otp#Fri Oct 11 12:21:11 IST 2019, mosip.kernel.keygenerator.symmetric-algorithm-length=256, resourcesFolder=\src\main\resources\, ivv._path.reports=/testRun/reports/mosip_reports.html, mosip.kernel.keygenerator.symmetric-algorithm-name=AES, mosip.kernel.crypto.symmetric-algorithm-name=AES, mosip.kernel.keygenerator.asymmetric-algorithm-length=2048, ivv.db.url=jdbc:postgresql://52.172.54.231:9001/  , documentUploadID=mosip.pre-registration.document.upload, ivv.email.server.pass=vmfWuq2b1@feb2020, mosip.kernel.crypto.asymmetric-algorithm-name=RSA, uin=7324384587, ivv.prereg.skip=age,IDSchemaVersion,UIN,localAdministrativeAuthority,parentOrGuardianName,parentOrGuardianRID,parentOrGuardianUIN,CNIENumber, ivv._path.auditlog=/testRun/reports/mosip_auditLogs.log, ivv.path.documents.folder=local/data/documents/, ivv.path.persona.sheet=local/PersonaSheet.csv, mosip.kernel.data-key-splitter=#KEY_SPLITTER#, ivv.path.documents.sheet=local/DocumentsSheet.csv, ivv.path.mappingfile=local/mapping.json, logsFolder=\testRun\logs\, ivv.path.configs.sheet=local/ConfigsSheet.csv, ivv.swagger.host=http://localhost:8081, ivv.path.rcpersona.sheet=local/RCUserSheet.csv, ivv.scenario.continueOnFailure=N, ivv.path.biometrics.sheet=local/BiometricsSheet.csv, ivv.prereg.version=v1, ivv.db.user=mosipuser, apiver=1.0, archiveFolder=\testRun\archive\, ivv.prereg.apiversion=1.0, ivv.path.partner.sheet=local/PartnerSheet.csv, ivv.mosip.host=https://qa2.mosip.net, registrationID=10004100740002520191003100437, ivv.prereg.otp.subject=Otp message, ivv.global.version=v1, ivv.email.server.host=outlook.office365.com, resultsFolder=\testRun\results\, ivv.path.scenario.sheet=local/ScenarioSheet.csv, ivv.email.server.user=mosip-test@technoforte.co.in, resourcesDataDocumentsFolder=\src\main\resources\data\documents\, ivv.path.idobject=local/IDObjectSchema.json, environment=https://int.mosip.io, ivv.db.pass=Mosip@123, ivv.regclient.skip=}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at io.mosip.ivv.orchestrator.Orchestrator.run(Orchestrator.java:217)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- run -->
        <test-method is-config="true" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:io.mosip.ivv.orchestrator.Orchestrator@6cc4cdb9]" started-at="2021-01-13T05:52:48Z" name="afterMethod" finished-at="2021-01-13T05:52:48Z" duration-ms="0" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=run status=FAILURE method=Orchestrator.run(int, io.mosip.ivv.core.dtos.Scenario, java.util.HashMap, java.util.HashMap, java.util.Properties)[pri:0, instance:io.mosip.ivv.orchestrator.Orchestrator@6cc4cdb9] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method is-config="true" signature="afterSuite()[pri:0, instance:io.mosip.ivv.orchestrator.Orchestrator@6cc4cdb9]" started-at="2021-01-13T05:52:49Z" name="afterSuite" finished-at="2021-01-13T05:52:49Z" duration-ms="288" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterSuite -->
      </class> <!-- io.mosip.ivv.orchestrator.Orchestrator -->
    </test> <!-- test1 -->
  </suite> <!-- Suite1 -->
</testng-results>
